version: '2'
services:
    gatling-app:
        image: gatling
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://gatling-mysql:3306/gatling?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    gatling-mysql:
        extends:
            file: mysql.yml
            service: gatling-mysql
